Added `disableThanks` option
changesets/changesets pull request #1255
Opened 2023-11-03 14:21 UTC by Kauhsa

Hi,

While thanking users in changelogs is commendable and makes sense for public projects or projects with a large amount of contributors, it served no purpose in our private packages and we felt that it cluttered our changelogs (for example, we had dozen entries in a single release, all prefixed with `Thanks @Kauhsa!`).

So, I added option `disableThanks` to `@changesets/changelog-github` to disable this behaviour.

2023-12-02 22:59 UTC, TheMikeyRoss commented
@Andarist @emmatown any update on this one?

2025-11-08 20:46 UTC, kachkaev commented
It'd be great to have this option indeed! In addition to accepting true/false, the option can also accept a RegExp for usernames. This will be useful for packages mostly maintained by one or two people. If 95% of changes are done by the same person, there's no need to say thanks to them every time. But a casual contributor can be mentioned.

In the meantime, I managed to disable _all_ thanks with a local pnpm patch:
https://github.com/kachkaev/routine-npm-packages/blob/6ed50ddbfcf99ec534717febb67f322a1c2c6321/patches/%40changesets__changelog-github.patch

2025-11-17 02:37 UTC, bluwy approved these changes

2026-04-23 08:11 UTC, beeequeue commented
related to my pr (#460) from very long ago :^)

2026-04-29 12:17 UTC, beeequeue reviewed
could you add support for a list of names as well as a boolean?

```json
{
  "disableThanks": ["beeequeue"]
}
```

then one could disable the thanks for people who commit often and still keep thanking rare contributors. :)

_this is what my original PR was trying to do_

2026-04-29 13:10 UTC, bluwy requested changes
Just noticed that I messed up the cherry-pick before and the option isn't called `disableThanks` anymore. Temporarily blocking this for now.

@beeequeue I think that idea makes sense too. Seems not too complicated to add so we can do it together in this PR.

2026-04-30 05:34 UTC, bluwy commented
Actually it's a bit tricky to refactor to handle the username filtering due to how it fetches the sources now, so I'm leaving it out from the changes.

2026-04-30 08:25 UTC, Andarist approved these changes

2026-05-04 02:20 UTC, bluwy approved these changes

2026-05-04 02:22 UTC, merged