feat: support read scoped registry from package json
changesets/changesets pull request #1470
Opened 2024-09-25 09:41 UTC by JounQin

close #1469

2024-09-25 10:03 UTC, JounQin commented
Not sure how to add related test cases.

cc @Andarist

2024-10-08 12:37 UTC, bluwy approved these changes
Seems good to me. Docs for `publishConfig['@scope:registry']` is limited, but it looks like it works according to https://github.com/changesets/changesets/pull/1272 (and the references within it, which also resulted in this PR?)

2024-10-11 09:11 UTC, JounQin commented
@Andarist Any time to review this PR?

2025-02-26 11:14 UTC, RodrigoHamuy commented
Alo, just checking when can we merge this as this is an issue for us since we are using `yarn` and private Github Packages.

2025-02-26 11:17 UTC, davgenaec approved these changes

2025-04-07 21:11 UTC, JounQin commented
friendly ping @Andarist

2025-04-08 07:49 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    (packageJson?.publishConfig?.[`${scope}:registry`] ||
is such a field supported by any tool? it feels off to me because `publishConfig` is specific to a package and thus there doesn't seem to be a need for a scopd registry field here, shouldn't `registry` already suffice all needs?

2025-04-08 07:53 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +    (packageJson?.publishConfig?.[`${scope}:registry`] ||
@Andarist No, `publishConfig#@scope:registry` takes higher priority, and please see #1469 for more details, when we have same `@scope`, but some are published to official npm registry publicly, and some are published to private npm registry, we need to use this PR's pattern.

2025-04-08 08:24 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    (packageJson?.publishConfig?.[`${scope}:registry`] ||
I confirmed that it works but npm doesn't have any tests for this behavior. It might also just be accidental that it works: https://github.com/npm/cli/blob/7fb624f32a4ae881824965c190bf6ae324eb83cb/lib/commands/publish.js#L12-L15

But given it works, I'm OK with supporting this.

2025-04-08 08:26 UTC, JounQin commented on packages/cli/src/commands/publish/publishPackages.ts
> -    isCustomRegistry(process.env.npm_config_registry)
I don't quite follow, what check exactly you mean?

2025-04-08 08:27 UTC, Andarist requested changes
Overall looks good but I left some comments that have to be addressed before we land this.

2025-04-08 08:28 UTC, Andarist commented on packages/cli/src/commands/publish/publishPackages.ts
> -    isCustomRegistry(process.env.npm_config_registry)
We should just bring back `|| isCustomRegistry(process.env.npm_config_registry)` here

2025-04-08 08:32 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +    npm_config_registry: registry,
Because there could be scoped and unscoped packages at the same time, both should be set correct registry, and this is already be checked with `if (scope) {`, or you mean:

```js
const envOverride: Record<string, string> = {
  [scope ? `npm_config_${scope}:registry`: npm_config_registry]: registry
}
```

2025-04-08 11:00 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    npm_config_registry: registry,
I'd have to double-check but most of the involved calls here are already specific to a single package - and likely they won't check anything about other packages anyway so there is a good chance that the above suggestion would work.

> Because there could be scoped and unscoped packages at the same time

I agree and that's why I think the current code could be seen as a footgun. Because configuring `"publishConfig": { "@scope:registry": ... }`shouldn't change `npm_config_registry`.

2025-04-08 11:23 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +    npm_config_registry: registry,
Yes, a scoped package can also has no scoped `publishConfig` setting, the unscoped config should cover this also. I just thought the current implementation covers all situations, do you prefer my proposed computed property instead?

2025-04-08 11:27 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +    npm_config_registry: registry,
When a scoped package config unscoped config, that config should takes lower priority then global scoped config, so I don't think we should change here. (It's really complicate, right.)

2025-04-08 11:44 UTC, JounQin commented on packages/cli/src/commands/publish/publishPackages.ts
> -    isCustomRegistry(process.env.npm_config_registry)
The env has already been checked in `getCorrectRegistry`.

2025-04-08 13:24 UTC, Andarist commented on packages/cli/src/commands/publish/publishPackages.ts
> -    isCustomRegistry(process.env.npm_config_registry)
currenlty only public packages are checked - this check could be responsible for checking private ones

2025-04-08 13:25 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +    npm_config_registry: registry,
overriding just a single env variable here sounds better than overriding two, so ye - the computed property approach sounds ok

2025-04-08 13:46 UTC, JounQin commented on packages/cli/src/commands/publish/publishPackages.ts
> -    isCustomRegistry(process.env.npm_config_registry)
Added back.

2025-04-08 13:48 UTC, JounQin commented
```console
🎁 info building bundles!
🎁 error /Users/JounQin/Workspaces/GitHub/changesets/packages/types/src/index.ts: Template literal types cannot have any substitution (56:18)
🎁 error
🎁 error   54 |     directory?: string;
🎁 error   55 |     registry?: string;
🎁 error > 56 |     [registry: `${string}:registry`]: string;
🎁 error      |                   ^
🎁 error   57 |   };
🎁 error   58 | };
🎁 error   59 | 
🎁 info If you want to learn more about the above error, check https://preconstruct.tools/errors
🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
```

I don't know what preconstruct is.

2025-04-11 06:07 UTC, JounQin commented
@Andarist Any further review?

2025-04-11 22:26 UTC, Andarist commented
@JounQin could you double-check the changes I made in https://github.com/changesets/changesets/pull/1470/commits/b932a830632bbb8f62564d388b90e1f8c86c9e0a ?

2025-04-11 22:51 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +    scope: undefined,
```suggestion
```

Given it's optional, we can omit this.

2025-04-11 22:52 UTC, JounQin commented
> @JounQin could you double-check the changes I made in https://github.com/changesets/changesets/pull/1470/commits/b932a830632bbb8f62564d388b90e1f8c86c9e0a ?

@Andarist Good cleaner refactor, LGTM, just left a unimportant comment/suggestion.

2025-04-11 22:56 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +      packageJson.publishConfig?.[`${scope}:registry`] ||
```suggestion
      packageJson!.publishConfig?.[`${scope}:registry`] ||
```

2025-04-11 23:00 UTC, JounQin commented on .changeset/eleven-panthers-talk.md
> +Support scoped registries configured using `package.json#publishConfig` and environment variables
I think we should be more specific mention what's the format in case that's really not well known, maybe linking to the `@npm/cli` or #1469 would be better.

2025-04-12 07:39 UTC, Andarist commented on packages/cli/src/commands/publish/npm-utils.ts
> +      process.env[`npm_config_${scope}:registry`];
last check before merging this - have you tried using this env variable? I know for sure it works with `packageJson.publichConfig` but I have not tested this with the env variable path

2025-04-12 08:13 UTC, JounQin commented on packages/cli/src/commands/publish/npm-utils.ts
> +      process.env[`npm_config_${scope}:registry`];
<img width="1024" alt="image" src="https://github.com/user-attachments/assets/7ac20bc6-7a6b-46f5-8e1d-a37b4b4a3050" />

@Andarist

2025-04-12 09:41 UTC, Andarist commented on .changeset/eleven-panthers-talk.md
> +Support scoped registries configured using `package.json#publishConfig` and environment variables
```suggestion
Support scoped registries configured using `package.json#publishConfig`
```

2025-04-12 09:41 UTC, merged